name: police-box
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install packages
        run: npm install --only=prod
      - name: Run the React.js build script
        run: npm run build
      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v2.1.0
        with:
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}